#!/usr/bin/env python3
"""Report kept modules that nothing reaches, so the manifest can drop them.

The plugin set is derived, so tightening the dependency budget silently strands
whatever existed only to serve the plugins that just got excluded. The closure
gate cannot see this -- an unreachable module imports fine -- so it needs its
own pass.

Reachability starts from the things that are genuinely entry points:

* ``geoips`` itself, and ``geoips_cli.main`` (the console script)
* every registered plugin module, since the registry loads those by path and no
  static import points at them
* the test modules

Anything under ``geoips/`` outside that closure is dead weight in the wheel.

This is advisory, not a gate: some modules are legitimately unreferenced public
API (``geoips.scripting`` exists for users to import), so removals go through
``prune/manifest.yaml`` after a human looks at the list.
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import deque

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import depbudget  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Modules that are entry points by nature: imported by users or loaded by the
# plugin registry rather than by another module.
#: Packages whose members are imported dynamically rather than by name.
DYNAMIC_PACKAGES = (
    "geoips.pydantic_models.v1",
    "geoips.utils.types",
)

ALWAYS_REACHABLE = (
    "geoips",
    "geoips.scripting",  # documented public API for OBP script mode
    "geoips._mini_ips",  # provenance, generated by slim.py
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("tree", nargs="?", default=os.path.join(ROOT, "build"))
    parser.add_argument(
        "--fail-on-orphans",
        action="store_true",
        help="exit 1 if any orphan is found (off by default -- see module docs)",
    )
    args = parser.parse_args(argv)

    paths, imports = depbudget.scan_tree(args.tree)

    roots: list[str] = [m for m in ALWAYS_REACHABLE if m in paths]
    # Plugins are loaded by the registry from a path, so nothing imports them.
    roots += [m for m in paths if m.startswith("geoips.plugins.")]
    # The CLI and the tests are the other real callers.
    cli_paths, cli_imports = depbudget.scan_tree(args.tree, package="geoips_cli")
    test_paths, test_imports = depbudget.scan_tree(args.tree, package="tests")

    # Fold the CLI and test graphs in: their `geoips.*` edges are what keep
    # modules like geoips.errors alive.
    for extra_paths, extra_imports in (
        (cli_paths, cli_imports),
        (test_paths, test_imports),
    ):
        paths.update(extra_paths)
        imports.update(extra_imports)
        roots += list(extra_paths)

    # These two packages are imported dynamically, so nothing statically points
    # at their members and every one of them would look orphaned:
    #   pydantic_models.v1 -- __init__.py:25 pkgutil.walk_packages + import_module
    #   utils.types        -- __init__.py:23 imports datatree_converters for its
    #                         registration side effect
    # The manifest keeps both as `/**` globs for the same reason; the rationale
    # lives there, on the globs that enforce it.
    for prefix in DYNAMIC_PACKAGES:
        roots += [m for m in paths if m == prefix or m.startswith(prefix + ".")]

    seen: set[str] = set()
    queue = deque(roots)
    while queue:
        module = queue.popleft()
        if module in seen or module not in imports:
            continue
        seen.add(module)
        queue.extend(imports[module].internal)
        # Importing a module imports its ancestor packages too, so their
        # __init__ side effects run and they are not orphans.
        parts = module.split(".")
        for i in range(1, len(parts)):
            ancestor = ".".join(parts[:i])
            if ancestor in paths:
                queue.append(ancestor)

    orphans = sorted(
        m
        for m in paths
        if m.startswith("geoips.") and m not in seen
        # Package markers are structural: judge the package by its members.
        and os.path.basename(paths[m]) != "__init__.py"
    )

    if not orphans:
        print(
            f"no orphans: all {len([m for m in paths if m.startswith('geoips.')])} "
            "geoips modules are reachable"
        )
        return 0

    print(f"{len(orphans)} kept module(s) that nothing reaches:\n")
    total = 0
    for module in orphans:
        path = paths[module]
        with open(path, encoding="utf-8", errors="replace") as handle:
            lines = sum(1 for _ in handle)
        total += lines
        print(f"  {os.path.relpath(path, args.tree):58s} {lines:5d} LOC")
    print(f"\n  {'total':58s} {total:5d} LOC")
    print(
        "\nEach is a candidate for `deny:` in prune/manifest.yaml. Check first "
        "that it is not public API someone imports directly."
    )
    return 1 if args.fail_on_orphans else 0


if __name__ == "__main__":
    sys.exit(main())
